/*
---------------------------------------
	Sounds.h
	
	Ljud-effekter till Magus
---------------------------------------
*/

void Ding( void );
void Swing( void );
void Swisch( void );
void Boing( void );
void Click( void );
void Hit( void );
void Bow( void );
void Summon( void );
void Zzap( void );
void Boomm( void );
void Ploing( void );
void Bong( void );
void Swoop( void );
